importar librerias

In [2]:
#importar librerias
import pandas as pd
import numpy as np

In [80]:
#leer el archivo

df_orcola = pd.read_csv('dataset\preETL\corrientes\departamentos_orcola.csv')
df_argenprop = pd.read_csv('dataset\preETL\corrientes\departamentos_argenprop.csv')

# concatenar los dos dataframes 
df = pd.concat([df_orcola, df_argenprop])

In [81]:
df

,enlace,address,price,expensas,tipo,superficie,cantidad_ambientes,cantidad_dormitorios,cantidad_banos,latitud,longitud
0,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Rivadavia 810 - Macrocentro,$ 430.000,NaN,NaN,50,2,NaN,1,NaN,NaN
1,https://www.estudioorcola.com/ficha.php?codigo...,Las Heras 766 - U.N.N.E.,$ 290.000,NaN,NaN,36,Mono,NaN,1,NaN,NaN
2,https://www.estudioorcola.com/ficha.php?codigo...,Franklin 756 - Zona Unne,230.000,NaN,NaN,35,MONO,NaN,1,NaN,NaN
3,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Wilde 12 - Micro Centro,$ 400.000,NaN,NaN,-,2,NaN,2,NaN,NaN
4,https://www.estudioorcola.com/ficha.php?codigo...,San Lorenzo 1180 - Zona Unne,$ 200.000,NaN,NaN,-,1,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
76,https://www.argenprop.com/departamento-en-alqu...,SALTA 300,$ 700.000,+ $250.000 expensas,Departamento,100 m² cubie.,3 ambientes,2 dorm.,2 baños,"-27,451162","-58,991714"
77,https://www.argenprop.com/departamento-en-alqu...,9 DE JULIO 300,$ 450.000,+ $110.000 expensas,Departamento,115 m² cubie.,5 ambientes,4 dorm.,3 baños,"-27,45421","-58,984207"
78,https://www.argenprop.com/departamento-en-alqu...,Av. Chaco 1100,$ 350.000,NaN,Departamento,62 m² cubie.,3 ambientes,2 dorm.,1 baño,"-27,47257","-58,982048"
79,https://www.argenprop.com/departamento-en-alqu...,"ARBO Y BLANCO 1100, Piso P.B.",$ 170.000,NaN,Departamento,30 m² cubie.,2 ambientes,1 dorm.,1 baño,"-27,464682","-58,99149"
80,https://www.argenprop.com/departamento-en-alqu...,AV SARMIENTO 700,Consultar precio,NaN,Departamento,80 m² cubie.,3 ambientes,2 dorm.,2 baños,"-27,445171","-58,980213"

In [82]:
#cambia mono por 1

import pandas as pd
import re

# Expresión regular para detectar "mono" o "monoambiente" en todas sus variantes
regex_exp = re.compile(r'\bmono(?:[-\s]?ambiente)?\b', re.IGNORECASE)

# Aplicar la expresión regular a la columna 'cantidad_ambientes' y cambiar los valores que cumplen la expresión regular por 1
df['cantidad_ambientes'] = df['cantidad_ambientes'].apply(lambda x: '1' if isinstance(x, str) and regex_exp.search(x) else x)

In [83]:
# transformar los datos de estring a numericos
df['price'] = df['price'].str.replace(r'[^\d]', '', regex=True)
df['expensas'] = df['expensas'].str.replace(r'[^\d]', '' , regex=True)
df['cantidad_dormitorios'] = df['cantidad_dormitorios'].str.replace(r'[^\d]', '', regex=True)
df['cantidad_banos'] = df['cantidad_banos'].str.replace(r'[^\d]', '', regex=True)
df['cantidad_ambientes'] = df['cantidad_ambientes'].str.replace(r'[^\d]', '', regex=True)
df['superficie'] = df['superficie'].str.replace(r'[^\d]', '', regex=True)

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['expensas'] = pd.to_numeric(df['expensas'], errors='coerce')

In [84]:

df['latitud'] = df['latitud'].str.replace(',', '.', regex=True)
df['longitud'] = df['longitud'].str.replace(',', '.', regex=True)
df['latitud'] = pd.to_numeric(df['latitud'])
df['longitud'] = pd.to_numeric(df['longitud'])

In [85]:
df

,enlace,address,price,expensas,tipo,superficie,cantidad_ambientes,cantidad_dormitorios,cantidad_banos,latitud,longitud
0,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Rivadavia 810 - Macrocentro,430000.0,NaN,NaN,50,2,NaN,NaN,NaN,NaN
1,https://www.estudioorcola.com/ficha.php?codigo...,Las Heras 766 - U.N.N.E.,290000.0,NaN,NaN,36,1,NaN,NaN,NaN,NaN
2,https://www.estudioorcola.com/ficha.php?codigo...,Franklin 756 - Zona Unne,230000.0,NaN,NaN,35,1,NaN,NaN,NaN,NaN
3,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Wilde 12 - Micro Centro,400000.0,NaN,NaN,,2,NaN,NaN,NaN,NaN
4,https://www.estudioorcola.com/ficha.php?codigo...,San Lorenzo 1180 - Zona Unne,200000.0,NaN,NaN,,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
76,https://www.argenprop.com/departamento-en-alqu...,SALTA 300,700000.0,250000.0,Departamento,100,3,2,2,-27.451162,-58.991714
77,https://www.argenprop.com/departamento-en-alqu...,9 DE JULIO 300,450000.0,110000.0,Departamento,115,5,4,3,-27.454210,-58.984207
78,https://www.argenprop.com/departamento-en-alqu...,Av. Chaco 1100,350000.0,NaN,Departamento,62,3,2,1,-27.472570,-58.982048
79,https://www.argenprop.com/departamento-en-alqu...,"ARBO Y BLANCO 1100, Piso P.B.",170000.0,NaN,Departamento,30,2,1,1,-27.464682,-58.991490
80,https://www.argenprop.com/departamento-en-alqu...,AV SARMIENTO 700,NaN,NaN,Departamento,80,3,2,2,-27.445171,-58.980213

In [5]:
data_universidades = {
    'Nombre': [
        'Facultad de Ciencias Agrarias (UNNE)',
        'Facultad de Ciencias Veterinarias (UNNE)',
        'Facultad de Ciencias Exactas y Naturales y Agrimensura (UNNE)',
        'Facultad de Derecho y Ciencias Sociales y Politicas (UNNE)',
        'Facultad de Humanidades (UNNE)',
        'Facultad de Odontología (UNNE)',
        'Facultad de Medicina (UNNE)',
        'Morgue de la Facultad de Medicina (UNNE)',
    ],
    'Latitud': [
        0.0,  # Latitud de Facultad de Ciencias Agrarias
        0.0,  # Latitud de Facultad de Ciencias Veterinarias
        0.0,  # Latitud de Facultad de Ciencias Exactas y Naturales y Agrimensura
        0.0,  # Latitud de Facultad de Derecho y Ciencias Sociales y Politicas
        0.0,  # Latitud de Facultad de Humanidades
        0.0,  # Latitud de Facultad de Odontología
        0.0,  # Latitud de Facultad de Medicina
        0.0   # Latitud de Morgue de la Facultad de Medicina
    ],
    'Longitud': [
        0.0,  # Longitud de Facultad de Ciencias Agrarias
        0.0,  # Longitud de Facultad de Ciencias Veterinarias
        0.0,  # Longitud de Facultad de Ciencias Exactas y Naturales y Agrimensura
        0.0,  # Longitud de Facultad de Derecho y Ciencias Sociales y Politicas
        0.0,  # Longitud de Facultad de Humanidades
        0.0,  # Longitud de Facultad de Odontología
        0.0,  # Longitud de Facultad de Medicina
        0.0   # Longitud de Morgue de la Facultad de Medicina
    ]
}

df_universidades = pd.DataFrame(data_universidades)

df_universidades_nombre = df_universidades['nombre']
df_universidades_nombre.to_csv(r'dataset\postETL\universidades_corrientes.csv' , index=False)

In [87]:
import pandas as pd
import numpy as np

# Función para calcular la distancia en cuadras entre dos puntos dados sus coordenadas de latitud y longitud
def calcular_distancia_cuadras(lat1, lon1, lat2, lon2):
    # Si lat1 o lon1 son NaN, asignarles los valores de lat2 y lon2
    
    
    if pd.isnull(lat1) or pd.isnull(lon1):
        return np.nan

    # Convertir las coordenadas a radianes
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    # Calcular la diferencia entre las coordenadas
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Calcular la distancia en metros usando la fórmula de Haversine
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    distancia_metros = 6371000 * c  # Radio de la Tierra en metros
    
    # Convertir la distancia a cuadras (1 cuadra = 100 metros)
    distancia_cuadras = distancia_metros // 100
    return int(distancia_cuadras)
    

# Calcular la distancia de cada departamento a cada universidad
# Calcular la distancia de cada departamento a cada universidad
df['distancias'] = df.apply(lambda dep: {uni['nombre']: calcular_distancia_cuadras(dep['latitud'], dep['longitud'], uni['latitud'], uni['longitud']) for _, uni in df_universidades.iterrows()}, axis=1)

# Expandir el diccionario de distancias en columnas separadas
distancias_df = df['distancias'].apply(pd.Series)
df = pd.concat([df.drop(columns=['distancias']), distancias_df], axis=1)

In [88]:
df

,enlace,address,price,expensas,tipo,superficie,cantidad_ambientes,cantidad_dormitorios,cantidad_banos,latitud,longitud,UNNE,UTN,UCES,UCuencaPlata,UCSalta,UGastónDachary,US21
0,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Rivadavia 810 - Macrocentro,430000.0,NaN,NaN,50,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.estudioorcola.com/ficha.php?codigo...,Las Heras 766 - U.N.N.E.,290000.0,NaN,NaN,36,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.estudioorcola.com/ficha.php?codigo...,Franklin 756 - Zona Unne,230000.0,NaN,NaN,35,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Wilde 12 - Micro Centro,400000.0,NaN,NaN,,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.estudioorcola.com/ficha.php?codigo...,San Lorenzo 1180 - Zona Unne,200000.0,NaN,NaN,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,https://www.argenprop.com/departamento-en-alqu...,SALTA 300,700000.0,250000.0,Departamento,100,3,2,2,-27.451162,-58.991714,15.0,12.0,10.0,11.0,9.0,8.0,2.0
77,https://www.argenprop.com/departamento-en-alqu...,9 DE JULIO 300,450000.0,110000.0,Departamento,115,5,4,3,-27.454210,-58.984207,10.0,6.0,6.0,5.0,1.0,1.0,8.0
78,https://www.argenprop.com/departamento-en-alqu...,Av. Chaco 1100,350000.0,NaN,Departamento,62,3,2,1,-27.472570,-58.982048,10.0,24.0,25.0,14.0,18.0,19.0,24.0
79,https://www.argenprop.com/departamento-en-alqu...,"ARBO Y BLANCO 1100, Piso P.B.",170000.0,NaN,Departamento,30,2,1,1,-27.464682,-58.991490,7.0,19.0,19.0,8.0,12.0,11.0,13.0
80,https://www.argenprop.com/departamento-en-alqu...,AV SARMIENTO 700,NaN,NaN,Departamento,80,3,2,2,-27.445171,-58.980213,20.0,6.0,4.0,16.0,12.0,12.0,15.0

In [89]:
df['longitud']=df['longitud'].astype(str)
df['latitud']=df['latitud'].astype(str)

In [94]:
df['latitud'] = df['latitud'].apply(lambda x: x.replace('.', ',') if isinstance(x, str) else x)
df['longitud'] = df['longitud'].apply(lambda x: x.replace('.', ',') if isinstance(x, str) else x)

In [95]:
df

,enlace,address,price,expensas,tipo,superficie,cantidad_ambientes,cantidad_dormitorios,cantidad_banos,latitud,longitud,UNNE,UTN,UCES,UCuencaPlata,UCSalta,UGastónDachary,US21
0,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Rivadavia 810 - Macrocentro,430000.0,NaN,NaN,50,2,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.estudioorcola.com/ficha.php?codigo...,Las Heras 766 - U.N.N.E.,290000.0,NaN,NaN,36,1,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.estudioorcola.com/ficha.php?codigo...,Franklin 756 - Zona Unne,230000.0,NaN,NaN,35,1,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.estudioorcola.com/ficha.php?codigo...,Avenida Wilde 12 - Micro Centro,400000.0,NaN,NaN,,2,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.estudioorcola.com/ficha.php?codigo...,San Lorenzo 1180 - Zona Unne,200000.0,NaN,NaN,,1,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,https://www.argenprop.com/departamento-en-alqu...,SALTA 300,700000.0,250000.0,Departamento,100,3,2,2,"-27,451162","-58,991714",15.0,12.0,10.0,11.0,9.0,8.0,2.0
77,https://www.argenprop.com/departamento-en-alqu...,9 DE JULIO 300,450000.0,110000.0,Departamento,115,5,4,3,"-27,45421","-58,984207",10.0,6.0,6.0,5.0,1.0,1.0,8.0
78,https://www.argenprop.com/departamento-en-alqu...,Av. Chaco 1100,350000.0,NaN,Departamento,62,3,2,1,"-27,47257","-58,982048",10.0,24.0,25.0,14.0,18.0,19.0,24.0
79,https://www.argenprop.com/departamento-en-alqu...,"ARBO Y BLANCO 1100, Piso P.B.",170000.0,NaN,Departamento,30,2,1,1,"-27,464682","-58,99149",7.0,19.0,19.0,8.0,12.0,11.0,13.0
80,https://www.argenprop.com/departamento-en-alqu...,AV SARMIENTO 700,NaN,NaN,Departamento,80,3,2,2,"-27,445171","-58,980213",20.0,6.0,4.0,16.0,12.0,12.0,15.0

In [96]:


df.to_csv('dataset\postETL\departamentos_chaco.csv', encoding='utf-8', index=True , sep=';')